// Copyright (c) 2024 by Alibaba.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

use actix_web::HttpRequest;
use log::info;
use serde::{Deserialize, Serialize};

pub mod authorization;
pub mod token_verifier;

pub mod error;
pub use error::*;

pub use crate::admin::{
    authorization::{Authorization, AuthorizerType},
    token_verifier::{TokenVerifier, TokenVerifierType},
};

/// Claims are the abstraction of the claims generated by the token verifier.
#[derive(Clone, Debug, Default, Serialize, Deserialize, PartialEq)]
pub struct Claims {
    pub issuer: String,
    pub subject: String,
    pub audiences: Vec<String>,
}

pub struct AuthorizationDecision {
    pub allowed: bool,
    pub reason: String,
}

pub enum Admin {
    InsecureAllowAll,
    DenyAll,
    Enforce(TokenVerifier, Authorization),
}

#[derive(Clone, Debug, Default, Deserialize, PartialEq)]
#[serde(tag = "mode")]
pub enum AdminConfig {
    #[default]
    InsecureAllowAll,
    DenyAll,
    Enforce {
        token_verifier: TokenVerifierType,
        authorizer: AuthorizerType,
    },
}

impl TryFrom<AdminConfig> for Admin {
    type Error = Error;
    fn try_from(value: AdminConfig) -> Result<Self> {
        match value {
            AdminConfig::InsecureAllowAll => Ok(Admin::InsecureAllowAll),
            AdminConfig::DenyAll => Ok(Admin::DenyAll),
            AdminConfig::Enforce {
                token_verifier,
                authorizer,
            } => Ok(Admin::Enforce(
                token_verifier.try_into()?,
                authorizer.try_into()?,
            )),
        }
    }
}

impl Admin {
    pub fn check_admin_access(&self, request: &HttpRequest) -> Result<()> {
        match self {
            Admin::InsecureAllowAll => {
                info!("Admin access granted as AllowAll mode is enabled");
                return Ok(());
            }
            Admin::DenyAll => {
                return Err(Error::AdminAccessDenied {
                    reason: "Admin access denied as DenyAll mode is enabled".to_string(),
                });
            }
            Admin::Enforce(token_verifier, authorizer) => {
                let claims = token_verifier.parse_and_verify(request)?;
                let decision = authorizer.authorize(claims, request)?;
                if decision.allowed {
                    Ok(())
                } else {
                    Err(Error::AdminAccessDenied {
                        reason: decision.reason,
                    })
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {

    use super::*;
    use serde_json::json;

    #[test]
    pub fn make_admin_object() {
        // basic (backwards compatible)
        let admin_config_json = json!({
            "mode": "InsecureAllowAll",
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let _admin = Admin::try_from(config).unwrap();

        // with invalid mode
        let admin_config_json = json!({
            "type": "AllowAll",
        });

        let config = serde_json::from_value::<AdminConfig>(admin_config_json);
        assert!(config.is_err());

        // enforce mode / regex authorizer with invalid role (bad regex)
        let admin_config_json = json!({
            "mode": "Enforce",
            "authorizer": {
                "type": "RegexAcl",
                "roles": [{
                    "subject": "Anonymous",
                    "allowed_endpoints": "(xyz"
                }]
            },
            "token_verifier": {
                "type": "BearerJwt",
                "signer_pairs": [{
                    "issuer": "oidc-1",
                    "public_key_path": "test_data/admin/public_key.pem"
                }]
            }
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let admin = Admin::try_from(config);
        assert!(admin.is_err());

        // with invalid role (duplicate role)
        let admin_config_json = json!({
            "mode": "Enforce",
            "authorizer": {
                "type": "RegexAcl",
                "roles": [{
                    "subject": "Anonymous",
                    "allowed_endpoints": "(xyz"
                },
                {
                    "subject": "Anonymous",
                    "allowed_endpoints": "(xyz"
                }]
            },
            "token_verifier": {
                "type": "BearerJwt",
                "signer_pairs": [{
                    "issuer": "oidc-1",
                    "public_key_path": "test_data/admin/public_key.pem"
                }]
            }
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let admin = Admin::try_from(config);
        assert!(admin.is_err());
    }

    // TODO: fix this test with Bearer token fixture
    #[ignore]
    #[test]
    pub fn check_requests() {
        let admin_config_json = json!({
            "mode": "Enforce",
            "authorizer": {
                "type": "RegexAcl",
                "roles": [{
                    "subject": "Anonymous",
                    "allowed_endpoints": "^/resource/a/.+/c$"
                }]
            },
            "token_verifier": {
                "type": "BearerJwt",
                "signer_pairs": [{
                    "issuer": "oidc-1",
                    "public_key_path": "test_data/admin/public_key.pem"
                }]
            }
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let admin = Admin::try_from(config).unwrap();

        // valid request
        let req = actix_web::test::TestRequest::post()
            .uri("/resource/a/b/c")
            .to_http_request();
        admin.check_admin_access(&req).unwrap();

        // invalid request
        let req = actix_web::test::TestRequest::post()
            .uri("/resource/b/b/c")
            .to_http_request();
        assert!(admin.check_admin_access(&req).is_err());
    }

    #[test]
    pub fn check_requests_wrong_role() {
        let admin_config_json = json!({
            "type": "InsecureAllowAll",
            "roles" : [{
                "id": "Steve",
                "allowed_endpoints": "^/resource/a/.+/c$"
            }]
        });

        let config: AdminConfig = serde_json::from_value(admin_config_json).unwrap();
        let admin = Admin::try_from(config).unwrap();

        let req = actix_web::test::TestRequest::post()
            .uri("/resource/a/b/c")
            .to_http_request();
        assert!(admin.check_admin_access(&req).is_err());
    }
}
