sockets = ["0.0.0.0:8080"]
auth_public_key = "/kbs/kbs.pem"
# Ideally we should use some solution like cert-manager to issue let's encrypt based certificate:
# https://cert-manager.io/docs/configuration/acme/
insecure_http = true

[attestation_token_config]
attestation_token_type = "Ear"
trusted_certs_paths = ["/kbs/as-public-key.pem"]

[as_config]
work_dir = "/opt/confidential-containers/attestation-service"
policy_engine = "opa"

[as_config.attestation_token_config]
duration_min = 5

[as_config.attestation_token_config.signer]
key_path = "/kbs/as-private-key.pem"

[as_config.rvps_config]
store_type = "LocalFs"
remote_addr = ""
